name: Kate McCarthy

# Provide the name for all of your other GitHub repos that relate to this class.
# If I substitute your username and the repo name in a GitHub URL like this:
#    `https://github.com/YOUR_GITHUB_USERNAME/REPO_NAME`
# I should find your repository.
repo_names:
  - Kingdom-Mystery-App
  - ATLAS-Kingdom-Mystery
  
# check in 1 v check in 2

# Provide any URLs for your Videos
10-ux-ui-criticism:
  - https://youtu.be/VgZCxclOmpg
  - https://youtu.be/eQgE6dzKqjw

# Provide any URLs for your Data Models assignment
11-models-from-data:
  - https://github.com/kimccarthy/CocktailAPIATLAS/tree/main/CocktailAPITake2
  
project-check-in-1:
  - https://github.com/kimccarthy/ATLAS-iOS-Fall-22/issues/2
